ScrollReveal().reveal('.libroabierto')
ScrollReveal().reveal('.ladoderecho',{ delay: 500 })
ScrollReveal().reveal('.formulario01',{ delay: 500 })
ScrollReveal().reveal('.titulo-testimonio',{ delay: 500 })
ScrollReveal().reveal('.carousel',{ delay: 500 })
ScrollReveal().reveal('.ficha-persona',{ delay: 700 })
ScrollReveal().reveal('.autor-datos',{ delay: 700 })
ScrollReveal().reveal('.final-ficha',{ delay: 700 })
ScrollReveal().reveal('.titulo-preguntas',{ delay: 500 })
ScrollReveal().reveal('.preguntas',{ delay: 700 })